//
//  ZonasData.swift
//  Adventure Kaan
//
//  Created by Marco Alonso Rodriguez on 16/05/23.
//

import UIKit

struct ZonaData {
    let nombre: String
    let imagen: UIImage
    let latitud: Double
    let longitud: Double
    let textoHistoria: String
}

var zonas : [ZonaData] = [
    ZonaData(nombre: "Museo Maya", imagen: UIImage(named: "bg_zonas_1")!, latitud: 19.57744800, longitud: -88.045490, textoHistoria: "Fundada en 1850 con el nombre de Noj Kaaj Santa Cruz Xbalam Naj K’ampokolche  y rebautizada con el nombre con el que se le conoce actualmente en honor a un gobernante yucateco socialista; también conocida como “El Pueblo de los Guerreros”, la ahora ciudad de Felipe Carrillo Puerto fue el santuario de los mayas cruzoob o mayas rebeldes durante la Guerra de Castas.Podrás disfrutar de los sabores de la gastronomía local degustando platillos típicos en el mercado de la ciudad, visitar la Parroquia de la Santa Cruz, y sentir el misticismo y la historia en el Santuario de la Cruz Parlante, un templo sagrado que marca el lugar dónde en 1850 las inspiraron a los mayas a continuar en la guerra contra los españoles.Localizada entre la Riviera Maya y la Gran Costa Maya, la ciudad de Felipe Carrillo Puerto es el punto de partida ideal para comenzar tu aventura por Maya Ka´an, región rica en historia, cultura, y tradiciones milenarias que aún se conservan."),
    
    ZonaData(nombre: "Museo Guerra de Castas", imagen: UIImage(named: "bg_zonas_2")!, latitud: 20.1967382, longitud: -88.3749427, textoHistoria: "Está ubicado en una ex hacienda que data del siglo XVIII, en el poblado de Tihosuco, donde vivió el líder indígena Jacinto Pat, principal promotor de la rebelión en contra de los españoles.Desde la Guerra de Castas, en 1847, el inmueble estuvo abandonado hasta que el gobierno del estado lo restauró e inauguró como museo el 24 de marzo de 1993.Su misión es la de exhibir, preservar y difundir entre la población de Quintana Roo los pasajes históricos de la rebelión armada de mediados del siglo XIX.El museo exhibe armas, pinturas y documentos de la Guerra de Castas, así como fotografías, maquetas y fichas informativas acerca de la fundación de Chan Santa Cruz, hoy Felipe Carrillo Puerto."),
    
    ZonaData(nombre: "ChichenItza", imagen: UIImage(named: "bg_zonas_3")!, latitud: 20.679141, longitud: -88.5682953, textoHistoria: "Comenzamos con la ciudad prehispánica de Chichén-Itzá, según el nombre con el que quedó registrada, en la lista del Patrimonio de la Humanidad de la UNESCO, en 1988.Para llegar a estos valiosísimos restos arqueológicos y uno de los monumentos mayas más visitados de todo México, nos desplazaremos hasta Tinum, a unos 180 kilómetros de Playa del Carmen y a unos 200 kilómetros de Cancún.Desde ambos puntos de partida existen servicios de autobuses turísticos, también se puede contratar la excursión en hotel o agencia o tomar un carro de alquiler.Las comunicaciones, en cualquier caso, son excelentes. Chichén Itzá está emplazada en Yucatán, donde los mayas fueron muy prolíficos a la hora de levantar sus edificios; tanto es así que a menudo a Yucatán se la denomina ‘Mayab’.Dentro de esta ciudad, muy bien conservada, de un período en que la civilización entró en decadencia, se encuentra el Templo de Kukulcán, reconocido como una de las Siete Maravillas del Mundo Moderno.Al ser una ciudad completa, tendremos la ocasión de hacer un recorrido prácticamente por todo tipo de instalaciones de estos pueblos: ‘canchas’ para juegos de pelota, templos, lugares de sacrificios como el Cenote Sagrado, emplazamientos de comerciantes o guerreros."),
    
    ZonaData(nombre: "Tulum", imagen: UIImage(named: "bg_zonas_4")!, latitud: 20.2149382, longitud: -87.429747, textoHistoria: "Aquí nuestros antepasados tuvieron buen gusto y construyeron su ciudad amurallada con vistas al Caribe.La Zona Arqueológica de Tulum se encuentra en plena Riviera Maya, a sólo 60 kilómetros de Playa del Carmen y a unos 180 de Cancún.El espectáculo resulta abrumador, así que si sufres de Síndrome de Stendhal ya puedes andarte con cuidado porque el vahído por belleza está garantizado.Las ruinas de la antigua Zamá (amanecer, en maya), están dentro del Parque Nacional de Tulum, un espacio natural en el que entra la imponente playa sobre cuyo acantilado se alza el complejo amurallado.Destaca El Castillo, una torre de vigilancia que se supone servía de faro para señalizar la costa a los barcos de mercancías.Hay mucho que disfrutar en esta zona del estado mexicano de Quintana Roo, pero debes tener en cuenta que la Zona Arqueológica es la más visitada de todo México tras Chichén Itzá y Teotihuacán, así que te aconsejamos que disfrutes de la experiencia arqueológica a primera hora de la mañana y ya luego programes el día, sin olvidarte de un buen chapuzón en la playa para observar las ruinas de Tulum desde el mar."),
    
    ZonaData(nombre: "Coba", imagen: UIImage(named: "bg_zonas_5")!, latitud: 20.4912382, longitud: -87.7326947, textoHistoria: "Nos quedamos en Quintana Roo para conocer las ruinas mayas precolombinas de Cobá.Su nombre original Co-Bah, significa agua abundante y vete bien preparado por si deseas combinar la visita con el baño en alguno de sus cinco lagos o cenotes que rodean las instalaciones arqueológicas.Cobá está ubicada a unos 100 kilómetros de Playa del Carmen y a unos 40 de Tulum.Es un lugar muy interesante, con una apariencia similar a Chinchén Itzá, pero aquí juegas con ventaja si huyes de las multitudes, ya que es la gran desconocida, por ser la menos visitada.Aprovecha y disfruta, porque se trata de la mayor ciudad comercial que los mayas edificaron en la zona de Yucatán.La subida a la pirámide es por tu cuenta y riesgo, ya que existen carteles de advertencias por todas partes.Es cierto que las vistas desde arriba son una pasada, con toda la jungla a tus pies.De todos modos debes tener cuidado porque ascenderás por una pendiente muy pronunciada, con 110 difíciles escalones que te llevarán hasta la cumbre, situada a 42 metros de altura y que la coronan como la pirámide más alta de todo Yucatán.Para ayudarte sólo existen unas grandes cuerdas ancladas a la cima. Así que ve con calma y mucho cuidado."),
    
    ZonaData(nombre: "Xaman-Ha", imagen: UIImage(named: "bg_zonas_6")!, latitud: 20.6145382, longitud: -87.083277, textoHistoria: "Estas son las ruinas mayas más cercanas a nuestro destino estrella, ya que se encuentran en la misma zona de Playa del Carmen.Antes de seguir, debes tener en cuenta que para visitar el poblado arqueológico debes solicitar el permiso al Centro del Instituto Nacional de Antropología e Historia de Quintana Roo.Una vez conseguido, podrás acercarte a las ruinas e informar de tu visita en el puesto de control de acceso a las instalaciones.Antes de la llegada de los españoles al Continente, Xaman há (Agua del Norte) era el nombre de toda Playa del Carmen.Te encontrarás en una ciudad con cierto estatus, ya que se trata del lugar en el que los mayas iniciaban su viaje de peregrinación hacia Cozumel, para rendir culto a la diosa maya del amor, Ixchel.La historia es bien romántica y la entrada al yacimiento arqueológico es gratuita."),
    
    ZonaData(nombre: "Xcaret", imagen: UIImage(named: "bg_zonas_7")!, latitud: 20.5790982, longitud: -87.119547, textoHistoria: "Al igual que ocurrió con Xamanhá, estas ruinas situadas a poco menos de 9 kilómetros de Playa del Carmen y a unos 75 de Cancún, gozaron de una posición privilegiada debido a su posición con respecto a Cozumel.La ciudad de Xcaret, antes de la época colonial, era conocida bajo el nombre de P´olé, algo así como ‘mercantil’, por lo tanto ya nos podemos hacer una idea de cuál era la actividad principal de la zona, de hecho fue uno de los puertos mercantes más importantes de la época.Además tendremos que valorar el hecho de que se haya descubierto que hubo asentamientos humanos desde el primer siglo de nuestra era, aunque la ciudad floreció a partir del año 600 y su mayor apogeo fue entre los siglos XI y XVI.Para llegar, tendrás que ir en dirección al Ecoparque del mismo nombre y luego acceder a las instalaciones del INAH."),
    
    ZonaData(nombre: "Uxmal", imagen: UIImage(named: "bg_zonas_8")!, latitud: 20.3588382, longitud: -89.788147, textoHistoria: "Esta es una recomendación encarecida: si estás por la zona de Mérida,  no puedes perderte la visita a Uxmal.Es una ciudad relativamente pequeña, pero de una singularidad extraordinaria.Uxmal fue declarada Patrimonio de la Humanidad en 1996 y bien vale el paseo, por otra parte muy cómodo, para encontrarse con las terribles caras del dios Chaac y los elaboradísimos ornamentos de sus edificios.Por supuesto, la Pirámide del Adivino es una auténtica maravilla y, con 32 metros, no resulta muy complicada su escalada.Parece que Uxmal puede significar algo así como ‘tres veces edificada’ y podría hacer referencia a la dedicación con que se aplicaron en la construcción, en la que se cree que participaron miles de obreros.Hoy es uno de los yacimientos mayas más importantes de México, junto a Chichén Itza y Tikal. Por cierto, tendrás la ocasión de toparte con divertidas iguanas a las que les encanta tomar el sol sobre las piedras de las ruinas."),
    
    ZonaData(nombre: "Palenque", imagen: UIImage(named: "bg_zonas_9")!, latitud: 17.484782, longitud: -92.048047, textoHistoria: "La Zona Arqueológica de Palenque merece, sin ninguna duda, uno de los primeros puestos del Top Ten de nuestra lista de las mejores ruinas mayas, pero se encuentran muy alejadas de la Riviera Maya, a casi 800 kilómetros de Cancún, en el estado de Chiapas y casi en la frontera con Guatemala.Aún así, puede que tú seas uno de esos aventureros que se toma un par de días de escapada y se aventura hasta allá para disfrutarlo.Lo cierto es que precisamente su lejanía es lo que hace que tenga menos visitas y por lo tanto te ofrezca una experiencia muy relajada.La ciudad se extiende sobre una superficie de 2,5 km2, aunque esto es sólo un 2% de lo que la jungla esconde de la extensión total de este Patrimonio de la Humanidad.Atento, amante de la Historia, porque estas en un enclave que hunde sus raíces en la antigua Lakam Ha, fundada en el 2.500 a. C.Te vas a quedar de piedra con la calidad de los bajorrelieves y las piezas del museo. Las máscaras y abalorios de los reyes mayas son alucinantes."),
    
    ZonaData(nombre: "Kohunlich", imagen: UIImage(named: "bg_zonas_10")!, latitud: 18.420782, longitud: -88.792647, textoHistoria: "Volvemos a Quintana Roo para llegar a la Zona Arqueológica de Kohunlich y aquí te vas a dar de bruces con la enormidad en toda la extensión de la palabra.21 acres de extensión salpicados por cientos de montículos, muchos de ellos aún sin excavar, aunque los que ya están al descubierto te van a ofrecer un viaje alucinante hacia el arte maya.En estos momentos es un lugar de absoluta actualidad, porque los equipos de arqueólogos continúan trabajando, sobre nuevos descubrimientos y a la vista de quienes nos paseamos por allá.El trazado comprende una gran variedad de edificios, con paredes esculpidas y una peculiar muestra iconográfica, canalizaciones de aguas de lluvia y multitud de detalles que hacen pensar que Kohulich fue una gran urbe maya, que sirvió de nexo de unión entre núcleos de otras zonas como Petén y Campeche.Además podrás combinar tu visita a las ruinas con el contacto más estrecho con la naturaleza, ya que la zona arqueológica se encuentra en mitad de la selva tropical.Prepárate para el avistamiento de un montón de especies de pájaros y reptiles."),
    
    ZonaData(nombre: "San Miguelito", imagen: UIImage(named: "bg_zonas_11")!, latitud: 21.0708382, longitud: -86.778947, textoHistoria: "En los últimos años Cancún ha realizado un gran esfuerzo por habilitar sus propias zonas arqueológicas y vas a poder disfrutar de un buen paseo por las instalaciones de San Miguelito y también con su Museo Maya, ubicado en un edificio muy moderno y con una arquitectura vanguardista espectacular.Allí te espera una buena dosis de lo mejorcito que legaron los mayas a su paso por la isla, que utilizaron Cancún como puerto de partida para mercadear desde Yucatán.Al parecer las ruinas de San Miguelito realmente estaban integradas con la zona arqueológica de El Rey, aunque ahora permanecen separadas por el bulevar Kukulcán.Da igual, porque tienes tiempo de sobra para disfrutar de los dos enclaves y del museo. En este último se exponen, a lo largo de 1350 m2, más de 350 piezas, algunas de ellas procedentes de los primeros vestigios óseos encontrados en en cuevas inundadas de Tulum: ¡14.000 años de Historia te esperan! Además también podrás contemplar piezas de los museos más importantes del país y exposiciones temporales.Menuda combinación: imponentes hoteles, zonas recreativas, maravillosas playas, la selva de San Miguelito, Zonas Arqueológicas y el nuevo Museo Maya de Cancún. ¡Planazo!."),
    
    ZonaData(nombre: "El Tajin", imagen: UIImage(named: "bg_zonas_12")!, latitud: 20.382182, longitud: -97.46617, textoHistoria: "Llegamos a la última recomendación de esta tanda sobre las 10 mejores ruinas mayas, aunque tendremos que volver sobre el tema.Piensa que en México existen más de 200 yacimientos mayas descubiertos y muchísimos más que aún quedan por descubrir.La Historia de una de las grandes civilizaciones del mundo y de este país es una fuente inagotable.Pero vayamos con la Zona Arqueológica El Tajín. Lo cierto es que tendremos que desplazarnos hasta la otra punta del país, hacia el estado de Veracruz, pero también es un trayecto que fascina a quienes pasan unas vacaciones en la Riviera Maya.De hecho suelen tomar el avión desde Cancún y realizar una escapadita de un par de días. Si tú eres de los que optan por ello, no puedes perderte las ruinas de El Tajín.Al margen de que te estamos recomendando la zona arqueológica más importante de la costa norte de Veracruz, lo cierto es que estas ruinas tienen algo muy especial.Lo notarás en cuanto vislumbres su pirámide, muy diferente al resto de todas las que hayas contemplado hasta ahora. Ello es porque los mayas que vivieron aquí decidieron decorarla con nichos, murales y relieves. ¡Una auténtica maravilla! Por cierto, los habitantes de El Tajín debían ser fans del Juego de Pelota, porque aquí se han encontrado nada más y nada menos que 17.La ‘Ciudad del Trueno’, declarada Bien Cultural por la UNESCO, también posee un museo en el que podrás empaparte de los aspectos más diversos e interesantes de la época y admirar frisos, columnas, bajorrelieves, esculturas, cerámica."),
    
]
